services:
  redpanda:
    image: redpandadata/redpanda:v24.3.9
    container_name: flight-analytics-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:9092
      - --pandaproxy-addr
      - HTTP://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - HTTP://localhost:8082
      - --schema-registry-addr
      - HTTP://0.0.0.0:8081
      - --rpc-addr
      - 0.0.0.0:33145
      - --advertise-rpc-addr
      - redpanda:33145
    ports:
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

volumes:
  redpanda_data: